version: "3.9"
services:
  app:
    build: .
    image: yashh2417/intellishelf-store:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
